@echo.off
cis
@echo.
      ...............................
@echo
@echo ...                         ...
@echo ... HORA DO ALMOCO :)       ...
@echo ...                         ...
@echo ...............................
@echo.
pause